---
version: "3.8"

services:

  #############
  # GeoServer #
  #############
  geoserver:
    image: camptocamp/geoserver:jetty-openshift-2.20.1
    user: $UID:$GID
    ports:
      - 61590:8080
    volumes:
      # Some server config including CORS for Jetty
      - ./config/web-inf/web.xml:/var/lib/jetty/webapps/geoserver/WEB-INF/web.xml
      # Directory to serve static files
      - ./config/styles/icons:/mnt/geoserver_datadir/www
      # Directory for local icons for styles
      - ./config/styles/icons:/mnt/geoserver_datadir/workspaces/geo/styles/icons:rw

  ########################
  # Database for geodata #
  ########################

  postgres:
    image: postgis/postgis:12-3.2-alpine
    user: postgres
    ports:
      - 61543:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  pgtileserve:
    image: pramsey/pg_featureserv:latest
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    
  pygeoapi:
    image: geopython/pygeoapi:latest
    ports:
      - 5000:80
    volumes:
      - ./config2.yml:/pygeoapi/local.config.yml  
    